/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.mycompany.proyect_silabo_unprg.Proyect_Silabo_Unprg;
import entidades.Docente;
import entidades.Usuario;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author jairoa
 */
public class JFDatosCompletarRegistro extends javax.swing.JFrame {

    private Usuario usuarioRecibido;
    private BufferedImage firma; // variable global en la clase del formulario

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFDatosCompletarRegistro.class.getName());

    /**
     * Creates new form JFDatosCompletarRegistro
     */
    public JFDatosCompletarRegistro(Usuario usuario) {
        initComponents();
        this.usuarioRecibido = usuario;

        Proyect_Silabo_Unprg.configurarCampoConPlaceholder(this.txtDni, "Ingrese su DNI");
        Proyect_Silabo_Unprg.configurarCampoConPlaceholder(this.txtNombres, "Ingrese sus Nombres Completos");
        Proyect_Silabo_Unprg.configurarCampoConPlaceholder(this.txtApellidos, "Ingrese sus Apellidos Completos");
        Proyect_Silabo_Unprg.configurarCampoConPlaceholder(this.txtGrado, "Ingrese su grado academico (Ingeniero, Magister, etc)");
        Proyect_Silabo_Unprg.configurarCampoConPlaceholder(this.txtCorreo, "Ingrese su correo electronico");

        actualizarProgreso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblLogoPanel1 = new javax.swing.JLabel();
        btnFinalizar1 = new javax.swing.JButton();
        btnCuentaStyle = new javax.swing.JButton();
        btnSubirFirma = new javax.swing.JButton();
        barraProgreso = new javax.swing.JProgressBar();
        jPanel5 = new javax.swing.JPanel();
        lblLogoG = new javax.swing.JLabel();
        lblTittle = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        separador = new javax.swing.JSeparator();
        lblApellidos = new javax.swing.JLabel();
        separadorPass = new javax.swing.JSeparator();
        lblGrado = new javax.swing.JLabel();
        txtGrado = new javax.swing.JTextField();
        separatorCorreo = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        separadorUsuario1 = new javax.swing.JSeparator();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        separatorCorreo1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 86, 163));

        btnFinalizar1.setBackground(new java.awt.Color(25, 118, 210));
        btnFinalizar1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnFinalizar1.setText("FINALIZAR REGISTRO");
        btnFinalizar1.setBorder(null);
        btnFinalizar1.setBorderPainted(false);
        btnFinalizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFinalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizar1ActionPerformed(evt);
            }
        });

        btnCuentaStyle.setBackground(new java.awt.Color(25, 118, 210));
        btnCuentaStyle.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        btnCuentaStyle.setText("CUENTA");
        btnCuentaStyle.setBorder(null);
        btnCuentaStyle.setBorderPainted(false);

        btnSubirFirma.setBackground(new java.awt.Color(25, 118, 210));
        btnSubirFirma.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnSubirFirma.setText("SUBIR FIRMA");
        btnSubirFirma.setBorder(null);
        btnSubirFirma.setBorderPainted(false);
        btnSubirFirma.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSubirFirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirFirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblLogoPanel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnFinalizar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
            .addComponent(btnCuentaStyle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSubirFirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblLogoPanel1)
                .addGap(18, 18, 18)
                .addComponent(btnCuentaStyle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubirFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFinalizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        barraProgreso.setStringPainted(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        lblLogoG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/isotipo_unprg(2).png"))); // NOI18N

        lblTittle.setFont(new java.awt.Font("Roboto ExtraBold", 1, 30)); // NOI18N
        lblTittle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTittle.setText("DATOS PERSONALES");

        lblNombres.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(51, 51, 51));
        lblNombres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNombres.setText("NOMBRES");

        txtNombres.setBackground(new java.awt.Color(242, 240, 240));
        txtNombres.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtNombres.setForeground(new java.awt.Color(153, 153, 153));
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombres.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombres.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });

        separador.setBorder(new javax.swing.border.MatteBorder(null));

        lblApellidos.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 18)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(51, 51, 51));
        lblApellidos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblApellidos.setText("APELLIDOS");

        separadorPass.setBorder(new javax.swing.border.MatteBorder(null));

        lblGrado.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 18)); // NOI18N
        lblGrado.setForeground(new java.awt.Color(51, 51, 51));
        lblGrado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGrado.setText("GRADO ACADEMICO");

        txtGrado.setBackground(new java.awt.Color(242, 240, 240));
        txtGrado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtGrado.setForeground(new java.awt.Color(153, 153, 153));
        txtGrado.setBorder(null);
        txtGrado.setCaretColor(new java.awt.Color(255, 255, 255));
        txtGrado.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtGrado.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtGrado.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtGrado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGradoKeyReleased(evt);
            }
        });

        separatorCorreo.setBorder(new javax.swing.border.MatteBorder(null));

        txtApellidos.setBackground(new java.awt.Color(242, 240, 240));
        txtApellidos.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtApellidos.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidos.setBorder(null);
        txtApellidos.setCaretColor(new java.awt.Color(255, 255, 255));
        txtApellidos.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtApellidos.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtApellidos.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidosKeyReleased(evt);
            }
        });

        lblDni.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 18)); // NOI18N
        lblDni.setForeground(new java.awt.Color(51, 51, 51));
        lblDni.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDni.setText("DNI");

        txtDni.setBackground(new java.awt.Color(242, 240, 240));
        txtDni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtDni.setForeground(new java.awt.Color(153, 153, 153));
        txtDni.setBorder(null);
        txtDni.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDni.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtDni.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDni.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDniActionPerformed(evt);
            }
        });
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
        });

        separadorUsuario1.setBorder(new javax.swing.border.MatteBorder(null));

        lblCorreo.setFont(new java.awt.Font("Roboto Condensed Medium", 1, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(51, 51, 51));
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCorreo.setText("CORREO INSTITUCIONAL");

        txtCorreo.setBackground(new java.awt.Color(242, 240, 240));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setBorder(null);
        txtCorreo.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCorreo.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtCorreo.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtCorreo.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorreoKeyReleased(evt);
            }
        });

        separatorCorreo1.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTittle)
                    .addComponent(lblLogoG)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo)
                            .addComponent(lblCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separatorCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separadorUsuario1)
                            .addComponent(txtDni)
                            .addComponent(txtGrado)
                            .addComponent(lblGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(separadorPass)
                            .addComponent(txtApellidos)
                            .addComponent(lblNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombres)
                            .addComponent(separador)
                            .addComponent(separatorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblLogoG)
                .addGap(27, 27, 27)
                .addComponent(lblTittle)
                .addGap(27, 27, 27)
                .addComponent(lblDni)
                .addGap(8, 8, 8)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separadorUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblApellidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorPass, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGrado)
                .addGap(8, 8, 8)
                .addComponent(txtGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separatorCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCorreo)
                .addGap(8, 8, 8)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(separatorCorreo1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizar1ActionPerformed
        // Obtener texto de los campos
        String dni = txtDni.getText().trim();
        String nombres = txtNombres.getText().trim();
        String apellidos = txtApellidos.getText().trim();
        String grado = txtGrado.getText().trim();
        String correo = txtCorreo.getText().trim();

        // Validar que no estén vacíos ni con los placeholders
        if (!Proyect_Silabo_Unprg.validarCamposSinPlaceholder(txtDni, txtNombres, txtApellidos, txtGrado, txtCorreo)) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos correctamente.", "Faltan datos", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Validar que se haya subido la firma
        if (firma == null) {
            JOptionPane.showMessageDialog(this, "Debe subir una imagen de firma en formato PNG.", "Falta la firma", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Crear objeto Docente y asociarlo al Usuario
        Docente d = new Docente(nombres, apellidos, grado, dni, correo, firma);
        //usuarioRecibido.setDocente(d);

        // Guardar en la lista principal
        //Proyect_Silabo_Unprg.usuarios.add(usuarioRecibido);
        Proyect_Silabo_Unprg.docentes.add(d);

        // Mostrar en consola
        System.out.println("==== REGISTRO COMPLETADO ====");
        //System.out.println(usuarioRecibido);
        System.out.println("================================");

        // Mensaje de éxito y volver al login
        JOptionPane.showMessageDialog(this, "Registro completado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        new JFLogeo().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnFinalizar1ActionPerformed

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtGradoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGradoKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_txtGradoKeyReleased

    private void txtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_txtApellidosKeyReleased

    private void txtDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDniActionPerformed

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_txtDniKeyReleased

    private void txtCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyReleased
        actualizarProgreso();
    }//GEN-LAST:event_txtCorreoKeyReleased

    private void btnSubirFirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirFirmaActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imagen PNG", "png"));

        int option = chooser.showOpenDialog(this);
        if (option == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                firma = ImageIO.read(file); // leer la imagen como BufferedImage
                JOptionPane.showMessageDialog(this, "Firma cargada correctamente.");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al cargar la firma: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSubirFirmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDatosCompletarRegistro(Proyect_Silabo_Unprg.usuarios.get(0)).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btnCuentaStyle;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnFinalizar1;
    private javax.swing.JButton btnSubirFirma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblLogoG;
    private javax.swing.JLabel lblLogoPanel;
    private javax.swing.JLabel lblLogoPanel1;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separadorPass;
    private javax.swing.JSeparator separadorUsuario1;
    private javax.swing.JSeparator separatorCorreo;
    private javax.swing.JSeparator separatorCorreo1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtGrado;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

    private void actualizarProgreso() {
        int progreso = 0;
        int totalCampos = 5;

        if (!txtDni.getText().trim().equals("Ingrese su DNI") && !txtDni.getText().trim().isEmpty()) {
            progreso++;
        }
        if (!txtNombres.getText().trim().equals("Ingrese sus Nombres Completos") && !txtNombres.getText().trim().isEmpty()) {
            progreso++;
        }
        if (!txtApellidos.getText().trim().equals("Ingrese sus Apellidos Completos") && !txtApellidos.getText().trim().isEmpty()) {
            progreso++;
        }
        if (!txtGrado.getText().trim().equals("Ingrese su grado academico (Ingeniero, Magister, etc)") && !txtGrado.getText().trim().isEmpty()) {
            progreso++;
        }
        if (!txtCorreo.getText().trim().isEmpty()) {
            progreso++;
        }

        int porcentaje = (progreso * 100) / totalCampos;
        barraProgreso.setValue(porcentaje);
    }
}
